name: deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUILD: '*/*/documentation,*/*'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for showLastUpdateTime to work
      - name: Init and update submodules
        run: |
          git submodule update --init --recursive --remote
      - name: Install dependencies
        id: install
        run: |
          yarn install
      - name: Build
        run: |
          yarn build
      - name: Release to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: wiki.iota.org
      - name: Update dependencies
        id: update
        if: always() && (steps.install.outcome == 'failure')
        run: |
          yarn install --no-immutable
      - name: Create PR to update dependencies
        id: pr
        if: always() && (steps.update.outcome == 'success')
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'bot/update-dependencies'
          delete-branch: true
          add-paths: |
            yarn.lock
          commit-message: Update dependencies
          title: '[BOT] Update dependencies'
          reviewers: 'Dr-Electron, jlvandenhout'
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
      - name: Fail job
        if: always() && (steps.pr.outcome == 'success')
        run: |
          exit 1
